In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(Path("C:/Users/sambu/OneDrive/Desktop/Gitllab/UTOR-VIRT-FIN-PT-05-2022-U-LOLC/13-Neural-Networks/Unit 13 Homework/Instructions/Resources/applicants_data.csv"))

# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Review the data types associated with the columns
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [4]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=['NAME', 'EIN'])

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [5]:
# Create a list of categorical variables 
categorical_variables= list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [7]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [8]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(encoded_data,columns=enc.get_feature_names_out(categorical_variables))

# Review the DataFrame
encoded_df.head(10)

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [9]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical=applicant_data_df.drop(columns=categorical_variables)
encoded_df =  pd.concat( [numerical,encoded_df], axis=1)

# Review the Dataframe
encoded_df.head(10)

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,1,31452,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,1,7508025,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
8,1,94389,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [10]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df['IS_SUCCESSFUL']

# Display a sample of y
y.head(10)

0    1
1    1
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    0
Name: IS_SUCCESSFUL, dtype: int64

In [11]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=['IS_SUCCESSFUL'])
# Review the features DataFrame
X.head(10)

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
5,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6,1,31452,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,1,7508025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
8,1,94389,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
9,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [12]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [13]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [14]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.loc[0])

# Review the number of features
number_input_features

116

In [15]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [16]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features +1)//2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [17]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1)//2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [18]:
# Create the Sequential model instance
nn = Sequential()

In [19]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [20]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [21]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

In [22]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [23]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [24]:
# Fit the model using 50 epochs and the training data
model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5748 - accuracy: 0.7210
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5532 - accuracy: 0.7310
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5501 - accuracy: 0.7312
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5483 - accuracy: 0.7310
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5462 - accuracy: 0.7317
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5450 - accuracy: 0.7333
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7334
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7346
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7340
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5423 - accuracy: 0.7340
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7350
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5413 - accuracy: 0.7353
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5410 - accuracy: 0.7348
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5399 - accuracy: 0.7374
Epoch 15/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7352
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7364
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7373
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5387 - accuracy: 0.7363
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7372
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7376
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7370
Epoch 22/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7382
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7374
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7379
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7382
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7389
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7392
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7382
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7386
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7401
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7397
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7388
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7395
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7399
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7394
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5335 - accuracy: 0.7412
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5333 - accuracy: 0.7388
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5334 - accuracy: 0.7394
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7393
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7399
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7408
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7403
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7388
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7395
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5319 - accuracy: 0.7412
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7389
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7409
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7413
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5326 - accuracy: 0.7413

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [25]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(
    X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5564 - accuracy: 0.7299 - 572ms/epoch - 2ms/step
Loss: 0.5564056038856506, Accuracy: 0.729912519454956

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [26]:
# Set the model's file path
file_path = Path("C:/Users/sambu/OneDrive/Desktop/Gitllab/UTOR-VIRT-FIN-PT-05-2022-U-LOLC/13-Neural-Networks/Unit 13 Homework/Instructions/Resources/AlphabetSoup.h5")

# Export your model to a HDF5 file
nn.save(file_path)

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [27]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [28]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = (number_input_features+1)//2

In [29]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 = (number_input_features+1)//2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

58

In [30]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [31]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=number_output_neurons, activation="sigmoid"))



# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 58)                6786

 dense_4 (Dense)             (None, 1)                 59

=================================================================
Total params: 6,845
Trainable params: 6,845
Non-trainable params: 0
_________________________________________________________________

In [32]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [33]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6023 - accuracy: 0.7122
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5577 - accuracy: 0.7283
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5531 - accuracy: 0.7285
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5509 - accuracy: 0.7293
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7292
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7302
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5479 - accuracy: 0.7306
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7307
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5470 - accuracy: 0.7312
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5462 - accuracy: 0.7320
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7319
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7329
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5451 - accuracy: 0.7319
Epoch 14/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7325
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7325
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7321
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5437 - accuracy: 0.7325
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7332
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5432 - accuracy: 0.7334
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7334
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5425 - accuracy: 0.7330
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7335
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7345
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5417 - accuracy: 0.7333
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7345
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5411 - accuracy: 0.7345
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5407 - accuracy: 0.7346
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5409 - accuracy: 0.7337
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5408 - accuracy: 0.7353
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7344
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7345
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7340
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7353
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5403 - accuracy: 0.7360
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5401 - accuracy: 0.7352
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7351
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7365
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5395 - accuracy: 0.7351
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7371
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5393 - accuracy: 0.7362
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5392 - accuracy: 0.7355
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7353
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7371
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5384 - accuracy: 0.7374
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5388 - accuracy: 0.7361
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7371
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7373
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7379
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5379 - accuracy: 0.7371
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5383 - accuracy: 0.7367

#### Alternative Model 2

In [34]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [35]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [36]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features+1)//2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

58

In [37]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [38]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))
nn_A2.add(Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(Dense(units=number_output_neurons, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 58)                6786

 dense_6 (Dense)             (None, 29)                1711

=================================================================
Total params: 8,497
Trainable params: 8,497
Non-trainable params: 0
_________________________________________________________________

In [39]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [40]:
# Fit the model
model_2=  nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 1.7073 - accuracy: 0.0271
Epoch 2/50
804/804 [==============================] - 1s 2ms/step - loss: 1.0779 - accuracy: 0.0223
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.9234 - accuracy: 0.0224
Epoch 4/50
804/804 [==============================] - 1s 2ms/step - loss: 0.8683 - accuracy: 0.0184
Epoch 5/50
804/804 [==============================] - 1s 2ms/step - loss: 0.8200 - accuracy: 0.0305
Epoch 6/50
804/804 [==============================] - 1s 2ms/step - loss: 0.8137 - accuracy: 0.0337
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7763 - accuracy: 0.0815
Epoch 8/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7650 - accuracy: 0.1614
Epoch 9/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7463 - accuracy: 0.1049
Epoch 10/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7324 - accuracy: 0.0242
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7217 - accuracy: 0.0299
Epoch 12/50
804/804 [==============================] - 1s 2ms/step - loss: 0.7144 - accuracy: 0.0375
Epoch 13/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6975 - accuracy: 0.0385
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6855 - accuracy: 0.0192
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6834 - accuracy: 0.0430
Epoch 16/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6937 - accuracy: 0.0343
Epoch 17/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6752 - accuracy: 0.0308
Epoch 18/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6826 - accuracy: 0.0608
Epoch 19/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6678 - accuracy: 0.0579
Epoch 20/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6558 - accuracy: 0.0517
Epoch 21/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6525 - accuracy: 0.0619
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6474 - accuracy: 0.0464
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6533 - accuracy: 0.0669
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6436 - accuracy: 0.0488
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6303 - accuracy: 0.0549
Epoch 26/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6245 - accuracy: 0.0644
Epoch 27/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6235 - accuracy: 0.0568
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6229 - accuracy: 0.0977
Epoch 29/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6181 - accuracy: 0.1277
Epoch 30/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6138 - accuracy: 0.1159
Epoch 31/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6122 - accuracy: 0.0810
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.6144 - accuracy: 0.0424
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6078 - accuracy: 0.0657
Epoch 34/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6061 - accuracy: 0.0636
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6019 - accuracy: 0.0583
Epoch 36/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6021 - accuracy: 0.0577
Epoch 37/50
804/804 [==============================] - 1s 2ms/step - loss: 0.6041 - accuracy: 0.0853
Epoch 38/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5976 - accuracy: 0.0520
Epoch 39/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5946 - accuracy: 0.0401
Epoch 40/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5954 - accuracy: 0.0182
Epoch 41/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5939 - accuracy: 0.0506
Epoch 42/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5922 - accuracy: 0.0223
Epoch 43/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5919 - accuracy: 0.0236
Epoch 44/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5922 - accuracy: 0.0155
Epoch 45/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5937 - accuracy: 0.0285
Epoch 46/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5946 - accuracy: 0.0245
Epoch 47/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5924 - accuracy: 0.0433
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5913 - accuracy: 0.0399
Epoch 49/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5915 - accuracy: 0.0607
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5925 - accuracy: 0.0325

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [41]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5564 - accuracy: 0.7299 - 334ms/epoch - 1ms/step
Loss: 0.5564056038856506, Accuracy: 0.729912519454956

In [42]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled, y_test, verbose=2)


# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 0s - loss: 0.5584 - accuracy: 0.7294 - 403ms/epoch - 2ms/step
Loss: 0.558363139629364, Accuracy: 0.7294460535049438

In [43]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled, y_test, verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 0s - loss: 0.5967 - accuracy: 0.0090 - 428ms/epoch - 2ms/step
Loss: 0.5966500639915466, Accuracy: 0.00897959154099226

### Step 3: Save each of your alternative models as an HDF5 file.

In [44]:
# Set the file path for the first alternative model
file_path = Path("C:/Users/sambu/OneDrive/Desktop/Gitllab/UTOR-VIRT-FIN-PT-05-2022-U-LOLC/13-Neural-Networks/Unit 13 Homework/Instructions/Resources/AlphabetSoupa1.h5")

# Export your model to a HDF5 file
nn_A1.save(file_path)

In [45]:
# Set the file path for the second alternative model
file_path =Path("C:/Users/sambu/OneDrive/Desktop/Gitllab/UTOR-VIRT-FIN-PT-05-2022-U-LOLC/13-Neural-Networks/Unit 13 Homework/Instructions/Resources/AlphabetSoupa2.h5")

# Export your model to a HDF5 file
nn_A2.save(file_path)